repos:
  - repo: local
    hooks:
      - id: kernel-fmt
        name: kernel-fmt
        language: system
        entry: bash -c 'cd kernel && cargo fmt'
        pass_filenames: false
        files: ^kernel/
      - id: kernel-clippy
        name: kernel-clippy
        language: system
        entry: bash -c 'cd kernel && cargo clippy -- -D warnings'
        pass_filenames: false
        files: ^(kernel|user_lib)/
      - id: user-lib-fmt
        name: user-lib-fmt
        language: system
        entry: bash -c 'cd user_lib && cargo fmt'
        pass_filenames: false
        files: ^user_lib/
      - id: user-lib-clippy
        name: user-lib-clippy
        language: system
        entry: bash -c 'cd user_lib && cargo clippy -- -D warnings'
        pass_filenames: false
        files: ^user_lib/
  - repo: https://github.com/crate-ci/typos
    rev: v1.39.0
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=lf"]
