//! System call numbers as a typed enum.
//!
//! Each variant corresponds to an entry in the kernel's `sys_call_table`,
//! where the discriminant equals the table index used in `EAX` for `int $0x80`.

/// System call numbers for the `int $0x80` ABI.
///
/// The `#[repr(u32)]` discriminant is placed directly into `EAX` when issuing
/// a system call. No intermediate `u32` conversion is needed at call sites.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
#[repr(u32)]
pub enum Syscall {
    Setup = 0,
    Exit = 1,
    Fork = 2,
    Read = 3,
    Write = 4,
    Open = 5,
    Close = 6,
    Waitpid = 7,
    Creat = 8,
    Link = 9,
    Unlink = 10,
    Execve = 11,
    Chdir = 12,
    Time = 13,
    Mknod = 14,
    Chmod = 15,
    Chown = 16,
    Break = 17,
    Stat = 18,
    Lseek = 19,
    Getpid = 20,
    Mount = 21,
    Umount = 22,
    Setuid = 23,
    Getuid = 24,
    Stime = 25,
    Ptrace = 26,
    Alarm = 27,
    Fstat = 28,
    Pause = 29,
    Utime = 30,
    Stty = 31,
    Gtty = 32,
    Access = 33,
    Nice = 34,
    Ftime = 35,
    Sync = 36,
    Kill = 37,
    Rename = 38,
    Mkdir = 39,
    Rmdir = 40,
    Dup = 41,
    Pipe = 42,
    Times = 43,
    Prof = 44,
    Brk = 45,
    Setgid = 46,
    Getgid = 47,
    Signal = 48,
    Geteuid = 49,
    Getegid = 50,
    Acct = 51,
    Phys = 52,
    Lock = 53,
    Ioctl = 54,
    Fcntl = 55,
    Mpx = 56,
    Setpgid = 57,
    Ulimit = 58,
    Uname = 59,
    Umask = 60,
    Chroot = 61,
    Ustat = 62,
    Dup2 = 63,
    Getppid = 64,
    Getpgrp = 65,
    Setsid = 66,
    Sigaction = 67,
    Sgetmask = 68,
    Ssetmask = 69,
    Setreuid = 70,
    Setregid = 71,
    Test = 72,
}
