[package]
name = "miniximg-cli"
version = "1.1.0"
authors = ["Poseidon <18646154381@163.com>"]
edition = "2024"
description = "Command-line tool for building, inspecting, editing, and interactively exploring Minix v1 filesystem images"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Poseidon-fan/linux-0.11-rs"
homepage = "https://github.com/Poseidon-fan/linux-0.11-rs/tree/master/miniximg/miniximg-cli"
documentation = "https://docs.rs/miniximg-cli"
keywords = ["minix", "filesystem", "disk-image", "cli", "linux-0-11"]
categories = ["command-line-utilities", "filesystem"]

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
miniximg = { version = "1.1.0", path = "../miniximg-core" }
miniximg-shell = { version = "1.1.0", path = "../miniximg-shell" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"

[[bin]]
name = "miniximg"
path = "src/main.rs"
