name: Deploy Tutorial Book

on:
  push:
    branches:
      - master
    paths:
      - 'tutorial/**'
      - '.github/workflows/deploy.yaml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-toc

      - name: Build Book
        run: |
          cd tutorial
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./tutorial/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
